### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by OBrein** [Incognito-Coder/Wiregen#1]
python3 wiregen.py --user * --pass *
Error 401

python wiregen.py -u * -p *
 File "wiregen.py", line 24
    print(f'PrivateK : {prvK}')
                             ^
SyntaxError: invalid syntax

**Comment by Incognito-Coder** [comment]
> python3 wiregen.py --user * --pass *
> 
> Error 401
> 
> 
> 
> python wiregen.py -u * -p *
> 
>  File "wiregen.py", line 24
> 
>     print(f'PrivateK : {prvK}')
> 
>                              ^
> 
> SyntaxError: invalid syntax

error 401 is an auth error.
maybe you send incorrect credentials,your account must have an active subscription.


about error below.
this happens when default __Python__ is sets to python 2
check output of:
~~~
python --version
~~~

**Comment by OBrein** [comment]
python --version
Python 2.7.18
Ubuntu 20.04 Server
Credentials is correct, this my 2-years plan account.

**Comment by Incognito-Coder** [comment]
solved.
try and tell me if stills

**Comment by OBrein** [comment]
It works, the configs have been successfully extracted.  Thank you.
