### ISSUE TITLE
What is uymgg1.com?

### ISSUE THREAD

**Issue by rallyemax** [Incognito-Coder/Wiregen#10]
The script uses two different hostnames to access the Surfshark API: `api.surfshark.com` and `api.uymgg1.com`

What is uymgg1.com?

Replacing all instances of `uymgg1` with `surfshark` in the script works.

Now, based on anecdotal reports, it does look like `uymgg1` may actually be a Surfshark URL, but a few things gave me spoofy vibes:
- The `surfshark.com` SSL certificate was issued by Cloudflare. The `uymgg1.com` certificate was issued by Let's Encrypt.
- The domain registration information for the two domains looks quite different.
- Browsing to https://uymgg1.com involves a noticeable delay before the site loads. But pinging `uymgg1.com` results in much faster response times than pinging `surfshark.com` (both from a Seattle server: 15ms versus 50ms).

If the `surfshark` domain works, perhaps consider switching to eliminate any confusion. I am not saying you are doing anything nefarious, but the unexpected nature of a strange URL combined with the three factors above made me a bit suspicious. It's why I changed all the URLs to `surfshark.com`, and I'm glad it worked because I am not willing to authenticate against `uymgg1` unless I see something from Surfshark claiming ownership of that URL.

Aside from that, thanks for throwing this together, so far it's working perfectly well. I'm curious, how did you figure out the correct sequence of steps, endpoints, and request fields/payload structure?

**Comment by Incognito-Coder** [comment]
> The script uses two different hostnames to access the Surfshark API: `api.surfshark.com` and `api.uymgg1.com`
> 
> What is uymgg1.com?
> 
i found it on ios version of surfshark vpn.
because this hostname is not censored in **Iran**
both domains are from surfshark.
you can trust it.
