### ISSUE TITLE
Wiregen confs need to be regenerated after a few days?

### ISSUE THREAD

**Issue by Inkapa** [Incognito-Coder/Wiregen#11]
I'm rather new to wireguard, so I don't know if this is normal behavior.

After a seemingly random amount of time (~1-2 weeks), all the .conf files generated by wiregen become unusable, as if they "expired"?
Wireguard doesn't seem to throw any errors, but I won't have any internet access. I tried switching servers, but the issue seems to affect all confs. Of course if I disconnect from wireguard, my internet connection comes back.

When it happens, if I regenerate the confs with wiregen, replace them in `/etc/wireguard` and try to reconnect, it fixes the problem and everything works fine until the confs "expire" again.

I'm not sure if this is an issue with:
- My wireguard installation
-  Surfshark
- Wiregen 
- My OS settings
- Something else entirely 

But I've got wireguard configured on two different computers both running Manjaro linux KDE. And the issue keeps happening on both computers. 

Switching servers, rebooting, reconnecting and so on doesn't seem to fix anything, the only fix I found is to regenerate the confs.

**Comment by Incognito-Coder** [comment]
this is normal.
surfshark and other vpn services reset each user privatekey per a week or sometimes one per a month.
everythings on your machine is ok.

**Comment by Inkapa** [comment]
Ah alright, thanks for the heads up!
