### ISSUE TITLE
Hide password behind astersiks or make password field empty

### ISSUE THREAD

**Issue by petRUShka** [Incognito-Coder/Wiregen#12]
Now password field is plain text and after it is typed anyone can see it behind your back. Which isn't standard behavior related to passwords.

**Comment by Incognito-Coder** [comment]
good hint.i updated script.check out [commit](https://github.com/Incognito-Coder/Wiregen/commit/8e93cc60c5eb7865eea27eb5f0d2fbe0f463db03)
