### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by J053Fabi0** [Incognito-Coder/Wiregen#13]
I installed it by pacman. `sudo pacman -S python3 wireguard-tools surfshark-wireguard`. I get this error when running `wiregen`.

```
Traceback (most recent call last):
  File "/usr/bin/wiregen", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by Incognito-Coder** [comment]
because a python library not installed on your system.
try:
`pip install requests`
