### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by dfmknz** [Incognito-Coder/Wiregen#15]
I already tried it while connected to vpn and the result is the same error. Yes, I'm using surfshark, and yes, my creds are correct. I will report back if it works after update & reboot.

**Comment by Incognito-Coder** [comment]
> I already tried it while connected to vpn and the result is the same error. Yes, I'm using surfshark, and yes, my creds are correct. I will report back if it works after update & reboot.

CloudFlare protection blocked these type of requests.
