### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by pitremj** [Incognito-Coder/Wiregen#6]
getting error 403 when trying to generate configs

**Comment by pitremj** [comment]
![image](https://user-images.githubusercontent.com/21046575/170369045-2bfb2f6a-4572-4a9b-8a7a-93dc2c0b32af.png)

**Comment by Incognito-Coder** [comment]
try with VPN and test.

**Comment by pitremj** [comment]
same error when connected to the VPN

**Comment by Incognito-Coder** [comment]
> same error when connected to the VPN

are you sure about your surfshark account?
correct email/password?
otherwise let me check.

**Comment by pitremj** [comment]
yea i had to connect to test with VPN let me know if there any debug logs i can provide

thanks

**Comment by mythbuster74** [comment]
Yeah I have the same issue now.  Running from CLI with python.  Worked around 2 weeks ago though.

**Comment by mythbuster74** [comment]
You get a 403 error from the login function, and the program quits.

**Comment by fpusersuggest** [comment]
hello same issue here. Just surfshark stopped to work on my openbsd box then I have tried to recreate the conf file but I have got 403. Obviously the login/pass are right.

**Comment by Incognito-Coder** [comment]
now i made changes on login function.
try if it work,then close issue.
thanks

**Comment by fpusersuggest** [comment]
it works! Thanks!
