### ISSUE TITLE
cant extract configs

### ISSUE THREAD

**Issue by M03ED** [Incognito-Coder/Wiregen#7]
when i enter my email and password this happen and dosen't save any private and public key
na config va na key ha ro hich kodoom zakhore nemikon
![Screenshot 2022-07-19 231646](https://user-images.githubusercontent.com/50927468/179825854-422151ba-10b6-4ca5-8d08-908adfa3d94a.png)
e

**Comment by Incognito-Coder** [comment]
before opening issue remember to carefully read the ReadME.
this error happens when you have not already installed wireguard in your system.

**Comment by M03ED** [comment]
ty its solved , its was first time i use linux , im newbie.
