### ISSUE TITLE
trackback issue

### ISSUE THREAD

**Issue by M03ED** [Incognito-Coder/Wiregen#8]
i tryed to extraxt my new wireguard configs but i got this error 

![image](https://user-images.githubusercontent.com/50927468/182036436-dee0799e-fafa-4ed2-943e-583e7d752668.png)
![image](https://user-images.githubusercontent.com/50927468/182036454-f213b1d7-31a3-46c5-9067-e02f5e826837.png)

**Comment by Incognito-Coder** [comment]
it's connection error.
maybe surfshark restricted in your country.
try it with VPN and tell if works.

**Comment by M03ED** [comment]
im using surfshark app but i got this again

**Comment by Incognito-Coder** [comment]
> im using surfshark app but i got this again

no problem,using nordvpn.
![Screenshot 2022-08-01 182231](https://user-images.githubusercontent.com/55095073/182163607-915f03a9-d1b9-461c-aed2-b6a1c7191e8a.png)
update your python to latest version and required pip packages and try.

**Comment by M03ED** [comment]
problem was from surfshark app , ubuntu cant use internet when i turn surfshark on , i use windscribe and problem solved

**Comment by M03ED** [comment]
> problem was from surfshark app , ubuntu cant use internet when i turn surfshark on , i use windscribe and problem solved

and i should say im using ubuntu with wsl
