### ISSUE TITLE
Fails after generating two configs

### ISSUE THREAD

**Issue by dontcrash** [Incognito-Coder/Wiregen#9]
Status: OK
 Register: True
 Valid: 2022-08-11T17:35:24+00:00
 Generating zip file
 Tirana Created Successfully.
 Algiers Created Successfully.
Traceback (most recent call last):
  File "/home/Nick/Wiregen/wiregen.py", line 216, in <module>
    main(sys.argv[1:])
  File "/home/Nick/Wiregen/wiregen.py", line 209, in main
    Builder(path)
  File "/home/Nick/Wiregen/wiregen.py", line 109, in Builder
    ip = socket.gethostbyname(i['connectionName'])
socket.gaierror: [Errno -2] Name or service not known

**Comment by Incognito-Coder** [comment]
>  Status: OK
>  Register: True
>  Valid: 2022-08-11T17:35:24+00:00
>  Generating zip file
>  Tirana Created Successfully.
>  Algiers Created Successfully.
> Traceback (most recent call last):
>   File "/home/Nick/Wiregen/wiregen.py", line 216, in <module>
>     main(sys.argv[1:])
>   File "/home/Nick/Wiregen/wiregen.py", line 209, in main
>     Builder(path)
>   File "/home/Nick/Wiregen/wiregen.py", line 109, in Builder
>     ip = socket.gethostbyname(i['connectionName'])
> socket.gaierror: [Errno -2] Name or service not known
> 

are you sure?
try again and tell me if problem stills.
mine is working fine(tested 2 hours ago)

**Comment by dontcrash** [comment]
> 

If it helps, I am running Ubuntu Server 22.04, python3 version 3.10.4

**Comment by Incognito-Coder** [comment]
> > 
> 
> If it helps, I am running Ubuntu Server 22.04, python3 version 3.10.4

i think your vps can't reach some hosts.
if you can, run it on local machine.

**Comment by dontcrash** [comment]
> > > 
> > 
> > 
> > If it helps, I am running Ubuntu Server 22.04, python3 version 3.10.4
> 
> i think your vps can't reach some hosts. if you can, run it on local machine.

It is a local machine, I have tried changing my DNS servers to Cloudflare 1.1.1.1 etc but the same issue happens. Not sure what's going on, I can see the gethostbyname() function is a DNS query, maybe the script should do a try/catch and throw a warning if a host fails but attempt to continue?

**Comment by Incognito-Coder** [comment]
yes.
i will fix it tomorrow.

**Comment by dontcrash** [comment]
If I can figure out why the DNS is failing there, I will let you know! I can confirm it is not a local cache, flushing it and trying again with a different nameserver produces the same result, super weird behaviour.

**Comment by Incognito-Coder** [comment]
> If I can figure out why the DNS is failing there, I will let you know! I can confirm it is not a local cache, flushing it and trying again with a different nameserver produces the same result, super weird behaviour.

Did you use vpn for this process?

**Comment by Incognito-Coder** [comment]
watch new commit [c493275](https://github.com/Incognito-Coder/Wiregen/commit/c493275878612f774a3c66be96333a13f3e6d2b2) i added try/catch.

**Comment by dontcrash** [comment]
> watch new commit [c493275](https://github.com/Incognito-Coder/Wiregen/commit/c493275878612f774a3c66be96333a13f3e6d2b2) i added try/catch.

Awesome! It makes it through a majority of the list now with only a few invalid hostnames
